### ISSUE TITLE
(removeblockoutline-1.1.2-1.20.1) works on 1.20.2, should be marked as compatible

### ISSUE THREAD

**Issue by Zorklis** [xzeldon/RemoveBlockOutline#2]
It works on 1.20.2 , fabric. Should be marked compatible so people know.
Does not crash, outline is removed/can be toggled.

**Comment by xzeldon** [comment]
I changed version on Modrinth but have no idea how to do it on Curseforge

**Comment by Zorklis** [comment]
I only download from Modrinth so it's important Curseforge is up to date. Thank you
